apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: mmikkili-ecommerce.centralindia.cloudapp.azure.com  # set this to your AKS cluster's public IP DNS name manually or via script
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
