name: "Deploy Nginx Ingress"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["App-build"]
    types:
      - completed
    
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest   # change to self-hosted if private AKS
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: az aks get-credentials -g "rg-ecommerce-aks" -n "ecommerce-aks" --overwrite-existing
        shell: bash
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Install Nginx ingress controller Helm chart
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          kubectl create namespace ingress-nginx
          helm install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --set controller.replicaCount=2 \
            --set controller.nodeSelector."kubernetes\.io/os"=linux \
            --set controller.service.type=LoadBalancer \
            --set controller.service.externalTrafficPolicy=Local
        shell: bash

      - name: Install Nginx ingress service
        run: |
          pwd; ls -la
          find . -name "ingress.yaml"
          kubectl apply -f ${{ github.workspace }}/k8s/ingress.yaml
        shell: bash
